chicago_10k:
    db_path: "postgresql://yuegong@localhost/st_tables"
    data_path: "data/chicago_open_data_10k/"
    shape_path: "data/shape_chicago_blocks/geo_export_8e927c91-3aad-4b67-86ff-bf4de675094e.shp"
    geo_chain: "block, tract, county, state"
    geo_keys: "blockce10, tractce10, countyfp10, statefp10"
    meta_path: "resource/chicago_10k/chicago_open_data.json"
    attr_path: "resource/chicago_10k/tbl_attrs_chicago_10k.json"
    profile_path: "resource/chicago_10k/profile_chicago_10k.json"
    col_stats_path: "resource/chicago_10k/col_stats_chicago_10k.json"
    idx_tbl_path: "resource/chicago_10k/idx_tbl_names.json"

chicago_1m:
    db_path: "postgresql://yuegong@localhost/chicago_open_data_1m"
    data_path: "/home/cc/data/chicago_open_data_1m/"
    shape_path: "/home/cc/data/shape_chicago_blocks/geo_export_8e927c91-3aad-4b67-86ff-bf4de675094e.shp"
    geo_chain: "block, tract, county, state"
    geo_keys: "blockce10, tractce10, countyfp10, statefp10"
    meta_path: "resource/chicago_1m/chicago_open_data.json"
    attr_path: "resource/chicago_1m/tbl_attrs_chicago_1m.json"
    profile_path: "resource/chicago_1m/profile_chicago_1m.json"
    col_stats_path: "resource/chicago_1m/col_stats_chicago_1m.json"
    idx_tbl_path: "resource/chicago_1m/idx_tbl_names.json"

data_prep:
    root_dir: os.path.dirname(os.path.abspath(__file__))
    app_token: "voGyQiv0JulAwW8e2YwTCUlBS"