chicago_10k:
    db_path: "postgresql://yuegong@localhost/st_tables"
    data_path: "data/chicago_open_data_10k/"
    shape_path: "data/shape_chicago_blocks/geo_export_8e927c91-3aad-4b67-86ff-bf4de675094e.shp"
    meta_path: "resource/chicago_10k/chicago_open_data.json"
    attr_path: "resource/chicago_10k/tbl_attrs_chicago_10k.json"
    profile_path: "resource/chicago_10k/profile_chicago_10k.json"
    idx_tbl_path: "resource/chicago_10k/idx_tbl_names.json"

chicago_1m:
    db_path: "postgresql://yuegong@localhost/st_tables"
    data_path: "data/chicago_open_data_10k/"
    meta_path: "data/chicago_open_data.json"
    shape_path: "data/shape_chicago_blocks/geo_export_8e927c91-3aad-4b67-86ff-bf4de675094e.shp"
    attr_path: "data/tbl_attrs_chicago_10k.json"
    profile_path: "data/profile_chicago_10k.json"